DB:
  Mode : 0
  MySQL:
    Write:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 3306

      User: "root"
      Pass: "123456"
      Charset: "utf8"
      MaxIdleConns: 10
      MaxOpenConns: 128
      ConnMaxLifetime: 60    # 连接不活动时的最大生存时间(秒)

      IsOpenReadDB: 0                     # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read 部分参数有效，否则Read部分参数直接忽略

    Read:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 3308                        #注意，非3306，请自行调整
      Prefix: "tb_"
      User: "root"
      Pass: "yourPassword"
      Charset: "utf8"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60


#################=====PostgreSQL====#####################################
  # 如果要使用postgresql数据库，请在 app/model 目录，将 users_for_postgres.txt 的内容直接覆盖同目录的 users.go 即可
  PostgreSql:
    IsInitGlobalGormPostgreSql: 0  # 随项目启动为gorm db初始化一个全局 variable.GormDbMysql（完全等于*gorm.Db）,正确配置数据库，该值必须设置为: 1
    SlowThreshold: 30
    Write:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 5432
      Prefix: "tb_"
      User: "postgres"
      Pass: "Secret2017~"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60

    IsOpenReadDb: 0            # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read  部分参数有效，否则Read部分参数直接忽略

    Read:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 5432
      Prefix: "tb_"
      User: "postgres"
      Pass: "secret2017"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
