Mode:
  Develop: true

log:
  MaxSize: 10    #每个日志文件最大容量，MB
  MaxBackups: 10 #保留旧文件的最大个数

DB:
  Type: 1  #1=启动mysql，2=启动PosetgreSQL

key:
  PrivateKey: "example_Key"
  Access_Token_OutTime: 7200    #2小时
  Refresh_Token_OutTime: 60480  #7天

Redis:
  DNS: "localhost:6379"
  DB: 0
  Password: ""

grpc:
  DNS: "127.0.0.1:5001"        #192.168.3.205


Login:
  AkOutTime: 72000  #2小时
  RkOutTime: 2592000 #3天



