global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 监听 MySQL Exporter
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  # 监听 Redis Exporter (新增)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # 监听 RabbitMQ Exporter (新增)
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']

  # 监听 Zipkin 自身指标
  - job_name: 'zipkin'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['zipkin:9411']
